### ISSUE TITLE
Plans for version 1.0 [WIP]

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#53]
We've run into a couple situations where some refactoring would result in a more sensible app.  Here's my WIP proposal (please feel free to contribute) for a version 1.0 that will include breaking changes.

Note: This isn't anything fancy, mostly just me putting most of the current issues into a list because it kind of needs to happen... please tell me if I forgot anything.

- [x] Handle message attachments properly #50 #52
- [x] Fix participants #31 #51 
- [x] Misc other `sendMessage` problems #52 #49 (Thanks @jlarky)
- [x] A call to `api.listen` should return the `stopListening` function rather than passing it to the callback.
- [x] Handle `listen` being called multiple times.
- [x] Naming consistency:
   - Naming conventions are a little all over the place.  This is mostly because Facebook... seems not to care about them.  I don't see any real reason to Facebook's naming scheme closely.  Examples of this can be seen in the objects returned by `api.getUserInfo` as well as the two following functions.
  - `api.getThreadList` : This returns a lot of potentially completely useless data, can we strip it down?
  - `listen` : The field names on message objects corresponding to attachments seem unnecessarily different.  Is there any reason to specify `sticker_url` vs `file_url` vs `hires_url`.  It seems like each non-text type could simply have a  `url` field.
- [x] See if the login process can be streamlined.
- [x] Remove hacky access token support.
- [x] Create group chats #56
- [x] Update documentation to 1.0
- [x] Documentation naming consistency
- [x] Add getThreadHistory

Testing:
- [x] Basic functionality (Send/receive messages, stickers, basic events)
- [x] Extra functionality (getThreadList, getUserInfo, getFriendsList, getUserId)
- [x] Documentation of tests (Insofar as there are instructions on how to set up the config file.)
- [x] Extra: Pages 

Extras:
- [x] Login approvals (2FA) #22
- [x] Login with cookie #46 
- [x] Get online users #47
- [x] Logout

Note: There have been several undocumented functions in the api for a while now.  Namely:
- archiveThread
- deleteThread
- deleteMessage
- getUrl
- searchForThread
- unarchiveThread

Just noting them here as it's easy to forget things that aren't in the README.

**Comment by blazeu** [comment]
Contribution guidelines? Coding style guidelines?

**Comment by bsansouci** [comment]
I don't think this project is big enough to require hard guidelines. We've been very loose regarding coding style, but that's partially because of FB's naming convention.

**Comment by JLarky** [comment]
Do you guys consider shortened start sequence? I noticed that you can use `listen` with just a loadMainPage and part of nullStateReq (makeDefaults and stuff). And considering #46 that means that you can start client with just one http request. I don't know if that makes much difference for many users, but it might :)

**Comment by Schmavery** [comment]
Yes, I think it's definitely worth revisiting the current login sequence to see if it can be streamlined.  I think @bsansouci tried to do this already, but maybe Facebook has changed on their end since then.  I also wouldn't mind moving the graph API token code to a different location, because I get the feeling it's not very useful.

**Comment by bsansouci** [comment]
You guys can track the progress [here](https://github.com/Schmavery/facebook-chat-api/tree/pre-release-v1.0)

**Comment by bsansouci** [comment]
Hey @webfreak7, @blazeu what do you guys think of [this](https://github.com/Schmavery/facebook-chat-api/commit/9abfb0a062ed031d75de042dfff6821f5aff6c34)?

**Comment by bsansouci** [comment]
@JLarky ^

**Comment by blazeu** [comment]
:+1:

Add ```share``` attachment type, and it's complete.
Also, is there any reason in using a bunch of ```if``` instead of ```switch``` ?

**Comment by bsansouci** [comment]
Hey @blazeu if you ever have to courage, feel free to write some contribution guidelines. I [tried](https://github.com/Schmavery/facebook-chat-api/commit/47c97ef81b063016ac913e3105f1569666cf469e) to make the code more consistent.

**Comment by blazeu** [comment]
Nah, I'll pass. I don't really have a good understanding of the code.

If you want to make the code more consistent, consider linting the code.
Put the linter's config into the repo (```.eslintrc```, ```.jshintrc```, etc) and maybe incorporate linting into the test.

**Comment by Schmavery** [comment]
Update: We're just in the process of getting the docs up to date and we expect to ship v1.0 before the end of the week.

**Comment by Schmavery** [comment]
Update: We were a little late, but v1.0 is shipped now :)
